# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: X.D. Open Documents
email: cto@xindong.com
description: >- # this means to ignore newlines until "baseurl:"
    心动网络 • 公开文档
repository: xindong/docs # for local usage
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://docs.xindong.com" # the base hostname & protocol for your site, e.g. http://example.com
permalink: '/:categories/:title.html'
twitter_username: xindong
github_username:  xindong

# Build settings
markdown: kramdown
#theme: jekyll-theme-primer
remote_theme: xdanger/jekyll-theme-notion
#theme_color: red
plugins:
  - jekyll-avatar                # https://github.com/benbalter/jekyll-avatar
  - jekyll-coffeescript          # https://github.com/jekyll/jekyll-coffeescript
  - jekyll-gist                  # https://github.com/jekyll/jekyll-gist
  - jekyll-feed                  # https://github.com/jekyll/jekyll-feed
  - jekyll-paginate              # https://github.com/jekyll/jekyll-paginate
  - jekyll-mentions              # https://github.com/jekyll/jekyll-mentions
  - jekyll-optional-front-matter # https://github.com/benbalter/jekyll-optional-front-matter
#  - jekyll-readme-index          # https://github.com/benbalter/jekyll-readme-index
  - jekyll-redirect-from         # https://github.com/jekyll/jekyll-redirect-from
  - jekyll-relative-links        # https://github.com/benbalter/jekyll-relative-links
  - jekyll-remote-theme          # https://github.com/benbalter/jekyll-remote-theme
  - jekyll-seo-tag               # https://github.com/jekyll/jekyll-seo-tag
  - jekyll-sitemap               # https://github.com/jekyll/jekyll-sitemap
  - jekyll-swiss                 # https://github.com/broccolini/swiss
  - jekyll-github-metadata       # https://github.com/jekyll/github-metadata
  - jemoji                       # https://github.com/jekyll/jemoji
#  - jekyll-category-pages
timezone: Asia/Shanghai
highlighter: rouge
date_format: "%Y-%m-%d"
#category_path: 'category'
#category_layout: 'category_index.html'
show_excerpts: true
#paginate: 100

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
